### ISSUE TITLE
Text not displayed properly in edit window

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#1]
When I go to edit some text that has been translated, I expected to see the source (English), and the current translation (French in my case) from Google Translate.

The screenshot shows what I see:

![image](https://user-images.githubusercontent.com/2512079/151836502-806613a6-87f5-4de6-bad6-97c8bcab49a0.png)

The French version is not showing, and there's a tag bracket showing at the end.

When I go to edit the translation, this is what I see (no source text):

![image](https://user-images.githubusercontent.com/2512079/151836801-79aea845-4e4a-44cb-8a35-9bd6c52dce3b.png)

**Comment by andrewhancox** [comment]
Source text now not visible in modal (probably going in as separate piece of work), but now populating original content box correctly.
