### ISSUE TITLE
Exception - Call to a member function get() on bool

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#11]
I changed my API key from a temporary one.

Immediately, the whole Moodle site stopped working. Every url now gives the following two error messages:

> Exception - Call to a member function get() on bool
> Exception - Call to a member function get() on bool

Debug info:
Error code: generalexceptionmessage
Stack trace:
line 83 of /filter/translations/filter.php: Error thrown
line 176 of /lib/filterlib.php: call to filter_translations->filter()
line 232 of /lib/filterlib.php: call to filter_manager->apply_filter_chain()
line 1488 of /lib/weblib.php: call to filter_manager->filter_string()
line 1233 of /lib/pagelib.php: call to format_string()
line 2849 of /lib/weblib.php: call to moodle_page->set_title()
line 73 of /index.php: call to redirect()
Exception - Call to a member function get() on bool
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 83 of /filter/translations/filter.php: Error thrown
line 176 of /lib/filterlib.php: call to filter_translations->filter()
line 232 of /lib/filterlib.php: call to filter_manager->apply_filter_chain()
line 1488 of /lib/weblib.php: call to filter_manager->filter_string()
line 1233 of /lib/pagelib.php: call to format_string()
line 2853 of /lib/outputrenderers.php: call to moodle_page->set_title()
line 1945 of /lib/setuplib.php: call to core_renderer->fatal_error()
line 390 of /lib/setuplib.php: call to bootstrap_renderer->__call()
line ? of unknownfile: call to default_exception_handler()

**Comment by andrewhancox** [comment]
Apologies - I'm doing a lot of very active work on this and need to build out the unit tests a bit more. There was an issue with handling errors from google translate, I've pushed a new version that will log the error properly - can you take a look?

**Comment by berthelemy** [comment]
Thanks Andrew,
I've added the new version, which has got rid of the error message above.
Now to find why the new API key isn't working.
