### ISSUE TITLE
Do we need to run cli/insert_spans.php

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#117]
We installed the content translations filter before the cli/insert_spans.php tool was created.

Our translations table already has more than 50,000 entries (created using the Google Translate integration).

Can we ignore the insert_spans tool? Or do we have to start again?

@jgramp - wondering if you might know the answer?

**Comment by jgramp** [comment]
I'm not entirely sure. As we don't use the auto translate feature. But we manually translate our content, so it may not be relevant in your instance. But for us we needed to make our manually translated content translation ready by running the cli tool, else updating any existing content without the spans added would mean the translations are lost when we update the original language content.

**Comment by andrewhancox** [comment]
Ignore it - the span tags get added to content when you use the atto editor so that translations don't immediately break when you make minor edits.
