### ISSUE TITLE
Pages being translated to random languages

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#119]
## Context

One of our installed language packs is Kinyarwanda.

## To replicate

1. Ensure your computer/browser is set to English
2. Go to: https://academy.cabi.org/login/index.php

## Expected behaviour

- Login instructions display in English
- After login, everything to display in English

## Actual behaviour

- Login instructions display in Kinyarwanda (highlighted in screenshot below)
- After login, everything is in English, as expected
 
![Capture d’écran 2022-06-13 à 07 25 26](https://user-images.githubusercontent.com/2512079/173285561-25b68e8f-b250-4e8e-9bd6-e8eb8bb12f73.png)

## Additional info

This is the HTML for the Authentication instructions. Before the translation plugin, we set up the multilang filter for Spanish-speaking users.

````
<span data-translationhash="73d5c3541509cc5fe1baf484d799ba74"></span>
<p>
    <span lang="en" class="multilang">Anyone can <a href="/login/signup.php">create an account</a> here to access our free-to-use resources.</span><span lang="es" class="multilang">Cualquier persona puede <a href="/login/signup.php">crear una cuenta</a> aquí para acceder a nuestros recursos de uso libre.</span></p>
<p>
    <span lang="en" class="multilang">If you wish to access the paid-for content, please speak to your normal CABI representative, or <a href="https://www.cabi.org/products-and-services/sales-information/meet-the-sales-team/" target="_blank">contact the sales team</a>.</span>
    <span lang="es" class="multilang">Si desea acceder al contenido de pago, por favor hable con su representante habitual de CABI, o <a href="https://www.cabi.org/products-and-services/sales-information/meet-the-sales-team/" target="_blank">contacte al equipo de ventas</a>.</span></p>
````

**Comment by berthelemy** [comment]
It turns out it's not just the login screen.

Here's a screenshot of the New Account screen, showing parts displaying in Arabic.

![Capture d’écran 2022-06-13 à 07 55 18](https://user-images.githubusercontent.com/2512079/173289012-b9f94329-e251-4daa-b27d-689b3c801207.png)

**Comment by berthelemy** [comment]
The only thing that's changed in the last few days is that we discovered we needed to install the [Atto plugin](https://github.com/andrewhancox/moodle-atto_translations), and so did that. 

Could that have had this effect?

**Comment by berthelemy** [comment]
Also noticed this occurring on the list of course categories (with the language set to English).

These category titles should be in English.

![Capture d’écran 2022-06-13 à 09 51 11](https://user-images.githubusercontent.com/2512079/173305812-c9edba13-e3ba-4396-b17d-b7be24a6d404.png)

**Comment by andrewhancox** [comment]
There may be multiple issues here.
The login screen - I would check the site with the filter disabled - my assumption would be that this would be getting handled by the language packs.

**Comment by berthelemy** [comment]
With the filter disabled (Off, but available), in an incognito browser window, the language on the login screen is displayed in English, as is the language on the account sign up screen.

With the filter enabled, in the same window, the login screen instructions are turned to Kinyarwanda, and the custom profile field labels on the sign up screen are displayed in Arabic.

**Comment by berthelemy** [comment]
It looks like the translation table is completely corrupted since adding the Atto plugin (that's the only correlating factor... which implies it might be the cause, but I can't be definite).

I'm coming across other content that is now appearing in a translated language (French in this case), when it should be displaying in English, the source language.

I'm on the verge of disabling the filter, deleting all the translations, and starting again. Is that my best course of action? I hope not, given the amount of money we've already spent on Google Translate.

**Comment by andrewhancox** [comment]
There was a serious bug in the caching that is now fixed - my suspicion is this was the root cause here.

I don't think the contents of the translation table will be corrupted.

**Comment by berthelemy** [comment]
All seems to be sorted. Thanks.
