### ISSUE TITLE
Strange translations

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#12]
See attached CSV showing the translations table for a couple of test pages.

The course content seems to be translated OK (id 477-486).

I'm not sure why id 455 is translating English (en) to Spanish (en). Same with id 468.

[mdl_filter_translations.csv](https://github.com/andrewhancox/moodle-filter_translations/files/8168501/mdl_filter_translations.csv)

**Comment by andrewhancox** [comment]
That's an annoying quirk of google translate that I've now accounted for - can you manually delete the translation and retry?

**Comment by berthelemy** [comment]
Thanks Andrew. That seems to have fixed it.

Closing now.
