### ISSUE TITLE
How to find out if Translate API is being called?

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#121]
We have pages with multiple missing translations, but they don't seem to be being sent to Google Translate for translation.

Is there any way to check this?

**Comment by berthelemy** [comment]
> There are events that fire when translations are created, updated or deleted so you could start looking in the system log. It’s also worth checking to see if the google_backoffonerror setting has been toggled to true due to API issues.

I'm probably looking in the wrong place, but there are no rows in mdl_events with eventtype LIKE  "%translat%"

google_backoffonerror is off.

**Comment by andrewhancox** [comment]
You need to look in the table logstore_standard_log

**Comment by berthelemy** [comment]
Thanks @andrewhancox I've looked in the logstore. There have been translations created today.

However, when I load up a course page, with the language selector set to Spanish (for example), it's still coming back as English, and nothing is added to the logstore.

**Comment by andrewhancox** [comment]
There was a serious bug in the caching that is now fixed - my suspicion is this was the root cause here.
