### ISSUE TITLE
Incorrect message shown in migrate fulltranslate CLI script.

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-filter_translations#124]
The translations/cli/migrate_filter_fulltranslate.php CLI script shows the following message:
This tool will copy translations from the filter_fulltranslate plugin into the filter_translations plugin.
**Any entries previously copied using this tool will be removed.**
To execute the task run this command again specifying --confirm 

However, previously copied/migrated entries are not removed. Running the migration script again will duplicate entries.

**Comment by andrewhancox** [comment]
Good spot, fixed.
