### ISSUE TITLE
Incorrect translations shown when cachingmode is set to Session or Application

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-filter_translations#126]
When cachingmode is set to Session or Application then changing the language still show the translations in the language in which the cache is generated. Once the translation is cached, then the same translation is displayed for other languages too.
If you purge the cache then the correct translations show for the selected language, but now changing to other languages still shows the translation of the cached language.

<img width="748" alt="image-2" src="https://user-images.githubusercontent.com/4531184/174203899-483b5324-fbfc-4c75-b132-670b3a9fe84c.png">

**Comment by andrewhancox** [comment]
Fixed and pushed.
