### ISSUE TITLE
Workaround: untranslated content (Google Translate)

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#136]
We are noticing that some content, including category descriptions, labels, course titles etc, are not getting translated automatically.

This may be because we're an early adopter, and there is "stuff" left over in the cache or the translation table.

Anyhow, a workaround is to:

1. Make sure the Google translate interface is configured
2. Switch to your site's default language
3. edit the item concerned
4. CUT the content (CTRL/CMD-X)
5. Save the item
6. Re-edit the item
7. PASTE the content (CTRL/CMD-V)
8. Test by switching to the new language

**Comment by andrewhancox** [comment]
You need to prune the table containing translated content - probably be deleting everything where the raw text = translated text and language = en

**Comment by berthelemy** [comment]
@andrewhancox  I'm not sure whether your proposed solution will work. **Every** string is "translated" from English to English. If we prune those, we'll just end up with another huge Google Translate bill as every string gets sent for translation again.

Really we'd be looking for where the substitutetext is in English and the targetlanguage is other than English, but I can't see any way to check for that in the table?

**Comment by andrewhancox** [comment]
That's what I meant - if the two strings are equal and the language is NOT set to English. Apologies for getting that the wrong way round.

**Comment by berthelemy** [comment]
Thanks @andrewhancox That seems to have worked
