### ISSUE TITLE
Google translate not translating all content

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#147]
We are still finding some content is going untranslated by Google Translate.

We know that the API is working, as we're able to get new courses translated OK.

On some older courses, some elements (eg. labels, pages) are remaining untranslated.

They do not exist anywhere in the content_translations table.

Might this be something to do with caching?

I have tried to remove the `<span>` with translation hashes. And tried clearing the content and then pasting it back in.

**Comment by berthelemy** [comment]
I wonder, should we remove the Atto translations filter plugin? Is it this that's causing our problems?

**Comment by andrewhancox** [comment]
Based on my understanding of your use case you don't need it.

**Comment by berthelemy** [comment]
Thanks @andrewhancox .

We'll remove that.

The documentation isn't particularly clear about what the atto_translations plugin is for. It implies that it's a necessary part of the set. I'd update the docs, but I can't work out what the plugin does.

**Comment by berthelemy** [comment]
I've noticed an interesting symptom:

- Content written in English (using a Label)
- Switch language to French
- **Content stays in English**
- Switch on inline translations
- Click on the edit translation button beneath the label
- Click on Edit Translations in the popup
- **The editor shows English and French side by side** (See screenshot)

So why isn't it displaying as French?

![Capture d’écran 2022-08-23 à 10 01 00](https://user-images.githubusercontent.com/2512079/186107696-83abcba0-9d27-4b35-89eb-51430b47c903.png)

**Comment by berthelemy** [comment]
And one more, probably related symptom:

- Content is written in English
![image](https://user-images.githubusercontent.com/2512079/186146397-58d9b0a1-441d-484d-a172-9e5e8c0f6b30.png)

- Switch language to Turkish. Moodle language pack switches to Turkish, but content remains displayed in English
![image](https://user-images.githubusercontent.com/2512079/186146500-3a2321e7-647f-45e2-a568-a7688fbdd7ba.png)

- Switch on in-line translation - content is displayed in Turkish
![image](https://user-images.githubusercontent.com/2512079/186146673-5c7391fb-ec03-4dfe-92aa-648b98b14741.png)

So, like the earlier, French, example, what do we need to do in order to make sure the translated content is displayed to the user? It seems very erratic. Some content is displaying OK. Others exhibit these symptoms.

**Comment by berthelemy** [comment]
Fixed following Andrew's input
