### ISSUE TITLE
translation icons appearing within links can't be opened - e.g. upcoming events block

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#15]
![image](https://user-images.githubusercontent.com/8575694/157353319-68b8d652-4b32-4261-9fa7-de0cd432a9f4.png)
In the upcoming events block, the translation icons appear within the link (< a > tag) so I can't click to access the translations, because it links instead to the event, rather than the translation.

**Comment by jgramp** [comment]
Yes, that works, but our translators won't know to do that necessarily. Is
there any way for the icon to be displayed after the </a> tag?
Jessica Gramp
Moodle Academy Manager
UTC+10:30 (until 3 Apr 2022)


***@***.***
moodle.com
[image: Twitter] <https://twitter.com/moodle> [image: Facebook]
<https://www.facebook.com/moodle/> [image: Youtube]
<https://www.youtube.com/moodlehq> [image: Moodle - Empowering educators to
improve our world] <https://moodle.com/>
[image: Moodle Academy: Develop your skills as a Moodle Edcuator,
Administrator, Designer and Developer.] <https://moodle.academy>

**Comment by andrewhancox** [comment]
I'm already doing everything I can to suppress other actions that may bind to the elements containing translation tags - it may be there is something I've missed or some other way to bind the event handler but I couldn't see it... The other possibility would be to alter the code that appends the button:
 $(elem).append(html);

And have this look to see if it's an a tag and if so append it to the parent element - but I've got a feeling this would not work as there could be multiple pieces of translated text within a single a tag...

Very hard to find the right compromise.
