### ISSUE TITLE
Section titles do not have Edit Translation button

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#153]
Using the standard Moodle topics course format.

When Inline Translations is switched on, all elements have an edit translation button, except the section headings (see screenshot).

![image](https://user-images.githubusercontent.com/2512079/186109421-a461913b-f77a-426d-8955-c8bb277ed627.png)

**Comment by rjnl** [comment]
Is "Section 2" the default section name?

The inline translation icons only get added when the section names have been edited, as shown below:

![image](https://github.com/andrewhancox/moodle-filter_translations/assets/4531184/e8e0dc07-0bf7-42da-9462-05fb5d09080a)

Topic 3, Topic 4 and Topic 6 are default section names, hence do not have the edit translation icons.

**Comment by berthelemy** [comment]
Thanks @rjnl  Got it!
