### ISSUE TITLE
Performance issues after upgrade of filter - site unusable

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#154]
We have just upgraded the content_translations filter to the version now available in the Moodle Plugins database (as directed by our Moodle).

At the same time, we remove the Atto_translations plugin as [we were told](https://github.com/andrewhancox/moodle-filter_translations/issues/147#issuecomment-1214819171) we didn't need it.

Now, pages that were working fine are now taking a minute or so to load, even the home page after login. This happens in English, and also in any available language.

The second time we load a page soon after, it seems to load quite a bit quicker. But come back a few hours later and the cache seems to have disappeared and the pages take an age again.

In order to work on the site, I have had to temporarily disable the content_translations filter. The performance improvement is huge.

Does anyone have any ideas as to what might be happening?

**Comment by andrewhancox** [comment]
Resolved
