### ISSUE TITLE
Cannot click on translation icon in section names in M4.0+

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-filter_translations#164]
In Moodle 4.0+, course sections can be toggled by clicking on the section/topic name.
Since the translation icon is appended to the section name, clicking on the translation icon just toggles the section.
It is no longer possible to open up the translation popup when you click on the translation icon after the section name.

**Comment by jgramp** [comment]
I think in some other similar cases you need to right-click, instead of left-click to launch the translation menu. Does that work in this case @rjnl ?
