### ISSUE TITLE
Batch translations?

### ISSUE THREAD

**Issue by marcocevoli** [andrewhancox/moodle-filter_translations#169]
Hi,

Can you pre-translate an entire course at once? I mean, can you populate the filter-translation table with content without opening each piece of content one by one?

Having all strings in one table (translated or not) would be useful to export that table from MySQL, work on it, and importing it back to the db. Not optimal, but it would be a (manual) way of exporting/importing the translations, while you implement a proper feature for that.

TIA

**Comment by andrewhancox** [comment]
A couple of people have asked for this and I've tried to think around the issue but the closest I can get to a solution would be some kind of spidering - if you look at the install.xml file you'll see that missed translations do get recorded.

**Comment by marcocevoli** [comment]
Thanks. I don't fully understand your answer, though. Do you mean that I can find the missing translation in the database? Last time I checked, I couldn't find them. Is there a command to trigger the inclusion of missing translation in the db?
