### ISSUE TITLE
Should the translation hash key be editable? What happens if someone changes this?

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#17]
Should the translation hash key be editable? What happens if someone changes this?
![image](https://user-images.githubusercontent.com/8575694/157353807-fecffcfb-75b9-4335-ae5b-bb2fae68898a.png)

**Comment by andrewhancox** [comment]
Changing this would allow you to connect a translation to a translation hash from a span tag, probably an edge case.

**Comment by jgramp** [comment]
ok, if this is something we might do, then I don't see a problem. As long
as people don't inadvertently change it and cause problems. I guess if this
happens we can always make this field read only. With a button to make it
editable if required. Restricted to those who have default language editing
rights. I'll add it to the end of our translation plugin scoping document
for future reference - in the 'out of scope for phases 1-3' section.
Jessica Gramp
Moodle Academy Manager
UTC+10:30 (until 3 Apr 2022)


***@***.***
moodle.com
[image: Twitter] <https://twitter.com/moodle> [image: Facebook]
<https://www.facebook.com/moodle/> [image: Youtube]
<https://www.youtube.com/moodlehq> [image: Moodle - Empowering educators to
improve our world] <https://moodle.com/>
[image: Moodle Academy: Develop your skills as a Moodle Edcuator,
Administrator, Designer and Developer.] <https://moodle.academy>
