### ISSUE TITLE
Shouldn't the hash key match if I was to manually md5 hash the HTML content?

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#18]
Shouldn't the hash key match if I was to manually md5 hash the content for HTML fields?

When I manually md5 hash plain text using https://passwordsgenerator.net/md5-hash-generator/ the hash matches what is shown in the translation hash key field.

When I manually md5 hash HTML content the hashes don't match - but I can't easily see the HTML of the original content, so I was just inspecting the element to get this content (including any spaces):

- Manual md5 hash is: 56D21880197DDFF3192FEF164C7F0833
- Translation hash key is: 860037a0861f2a60213c5e6d035cb907

![image](https://user-images.githubusercontent.com/8575694/157355809-750af4af-dc47-4e33-a684-648930634922.png)
v
![image](https://user-images.githubusercontent.com/8575694/157354509-37f30360-0a1b-428b-9378-7e16c21f6595.png)

**Comment by andrewhancox** [comment]
A few possibilities:
I strip any leading/trailing spaces before generating the hash
The span gets removed before hashing
If you have filters running after the translation filter then those will alter the text before it's hashed

**Comment by jgramp** [comment]
Yes, these all sound sensible.
Jessica Gramp
Moodle Academy Manager
UTC+10:30 (until 3 Apr 2022)


***@***.***
moodle.com
[image: Twitter] <https://twitter.com/moodle> [image: Facebook]
<https://www.facebook.com/moodle/> [image: Youtube]
<https://www.youtube.com/moodlehq> [image: Moodle - Empowering educators to
improve our world] <https://moodle.com/>
[image: Moodle Academy: Develop your skills as a Moodle Edcuator,
Administrator, Designer and Developer.] <https://moodle.academy>
