### ISSUE TITLE
Do Moodle language strings get stored in the language pack?

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#2]
I wasn't expecting to be able to translate the core Moodle strings using this interface.

Do any edits get stored in the language pack?

![image](https://user-images.githubusercontent.com/2512079/151837511-1f2ffd69-70cf-4a6e-8036-19b93a0fd35d.png)

**Comment by andrewhancox** [comment]
No - the tool translates any filtered text which will sometimes contain strings straight from the language pack. The tool looks for a translation from an installed language pack before calling out to google or leaving it untranslated.
