### ISSUE TITLE
Incorrect way to access globals in mustache template

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-filter_translations#20]
I get file not found error when clicking the "Edit translation" button in the modal. 

This is because in file `/template/translationdetailsmodalbody.mustache`
` {{config.wwwroot}} `
should be 
`{{globals.config.wwwroot}}`

See: https://docs.moodle.org/dev/Templates#Access_to_globals

**Comment by andrewhancox** [comment]
Merged - worked on 3.9... can you confirm which version you're testing on?

**Comment by rjnl** [comment]
I'm testing with Moodle 3.11.x on Windows.

**Comment by andrewhancox** [comment]
That'll be it then - I'm an LTS die-hard...

**Comment by berthelemy** [comment]
@andrewhancox Are you saying this plugin won't work on Moodle 3.11? We're just about to upgrade...

**Comment by andrewhancox** [comment]
It will be fine in 3.11 - Just Rajneel and I are testing in different versions.
