### ISSUE TITLE
remove background colour from icon in nav bar

### ISSUE THREAD

**Issue by RichieLef** [andrewhancox/moodle-filter_translations#24]
There is some CSS which is adding background colour to the icon in the nav bar. 

Currently it appears like this:
![image](https://user-images.githubusercontent.com/102128709/159400915-42abbae4-ff98-41c1-b578-fee444210b7c.png)
... removing the background colour corrects the issue:
![image](https://user-images.githubusercontent.com/102128709/159401016-88e557e2-3383-4e5b-b288-56beab83c5c5.png)

The relevant code is:
```
[class*=" icon-translate-"]:before
{
background-color: #fff;
}
```

_(screenshot from CSS inspector in Chrome):_
![image](https://user-images.githubusercontent.com/102128709/159401094-810a0b6a-2e10-41b1-8ac2-066ded865f89.png)

**Comment by andrewhancox** [comment]
Fixed
