### ISSUE TITLE
The <i> tag in the navbar should be wrapped in an <a> tag & some extra classes to help styling

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#25]
![image](https://user-images.githubusercontent.com/8575694/159420605-497a4b49-af90-423a-9a0d-a6fe1ad005e4.png)

The < i > tag needs to be wrapped in an < a > tag with the navlink class applied there instead of the div tag that wraps it. 
So this code should work:

`<div class="popover-region dropdown translation-icon-wrapper">
<a class="nav-link d-inline-block popover-region-toggle position-relative icon-no-margin" href="#" role="button">
    <i class="icon icon-translate-default navbar-icon" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    </i>
</a>`

Note the 2 new classes on the < div > (translation-icon-wrapper) and < i > (navbar-icon) so we can style these.
And the navlink class applied on the < a > tag instead of the < div > tag that wraps it.

**Comment by jgramp** [comment]
If this css doesn't work for LMS, we can always submit this later as a pull-request once we've done more testing, or just apply it our side. It may just look a bit out of wack until fixed. This is what I was thinking would fix the icon being rectangular instead of square, but this may only apply to Workplace:

Because the icon is not a square we need to add the following to the css:

.navbar.fixed-top .translation-icon-wrapper{
margin-top: 4px;
}

.navbar.fixed-top .icon-translate-default{
padding: 6px 10px 6px 10px;
}

**Comment by andrewhancox** [comment]
Done
