### ISSUE TITLE
I edited one of two stale translations and now the second one has disappeared from the list

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#29]
![image](https://user-images.githubusercontent.com/8575694/159589607-0e3e3a07-cb89-4b23-8d8b-b2bc5b09b671.png)
I edited one of two stale translations and now the second one has disappeared from the list and it's saying there are none left.
What happened to the second stale translation that I didn't update?

**Comment by jgramp** [comment]
I think I know what happened. The Page changed, so there were no translations on the new page. Because it was picking up the translation manager page as the new page probably. So I think we need to store the page and reload it when we have saved a translation, so you are taken back to the original list of stale translations for the original page you were on.

**Comment by andrewhancox** [comment]
Fixed
