### ISSUE TITLE
Rename 'Issue' to 'Translation status' on the Manage translation issues‍‍​‍‍ page.

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#30]
![image](https://user-images.githubusercontent.com/8575694/159589943-68756369-ce6f-416c-861a-84d750aae673.png)
Rename 'Issue' to 'Translation status' on the Manage translation issues‍‍​‍‍ page.

**Comment by andrewhancox** [comment]
Again - I think this would confuse what this report is showing. (feel free to reopen any of these issue BTW)

**Comment by jgramp** [comment]
Since you renamed the column heading to 'Status' ([Issue 41](https://github.com/andrewhancox/moodle-filter_translations/issues/41)), I think it makes sense to make it simply 'Status' here too.

Also, does 'Status' work better now if we have the page title of 'Pending Translations'? See: [Issue 40](https://github.com/andrewhancox/moodle-filter_translations/issues/40)

**Comment by andrewhancox** [comment]
Done
