### ISSUE TITLE
P3: Filter by language and automatically do this based on the logged in language. 

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#31]
P3: Filter by language and automatically do this based on the logged in language. Automatically filter by the language chosen in the top Moodle language menu and display this clearly on the 'Manage translations' pages and reports.

We only want to see translations in the current language (selected in the Moodle language menu). Translators won't care about other languages.

The current language should automatically filter this table of translations to the current language. So when I am looking a German I should only see the 'de_wp' translations listed. Also, translators won't understand de_wp necessarily, so we should clearly write this, like we do on the Create translation page:

![image](https://user-images.githubusercontent.com/8575694/159598247-25d83916-bb82-440e-b057-d70086cf38f1.png)

Non urgent feature: We should add a help icon telling people to use the standard Moodle language selector in the navigation bar to select this language permanently.

Translators will be going in and making translations in their language, so they will expect everything to be set to this as they work. They won't want to have to manually filter anything. 

The table should still display the Translation language column, but the above text will make this clear that this means German / Deutsch.

Currently all languages are showing in the table - no one will need to see this, except perhaps the site admins if they want to get a overview of all translations:
![image](https://user-images.githubusercontent.com/8575694/159596671-bc9a38fa-5da3-422c-95ef-02ac19ed083a.png)

**Comment by jgramp** [comment]
The **stale** filter seems to already filter by the Moodle language selected in the navbar, whereas the missing and any/all filters don't seem to yet.

**Comment by andrewhancox** [comment]
Done

**Comment by jgramp** [comment]
COnfirmed signed off.
The tables now filter auotmaticallhy by the language in the language bar, but the language doesn't get passed through to the subsequent pages: https://github.com/andrewhancox/moodle-filter_translations/issues/94

**Comment by jgramp** [comment]
I think this is an issue with the de_wp languages, not redirecting to de
