### ISSUE TITLE
Add 'up to date' in the filter list for issue / 'translation status' and rename 'Any' to 'All'

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#32]
![image](https://user-images.githubusercontent.com/8575694/159590482-62168d21-922d-40d7-8442-50f90b19c32c.png)

Add 'up to date' in the filter list for issue / 'translation status'
You should be able to filter to see all the 'up to date' translations.

The Options should be:
All
Missing
Stale
Up to date

Also, rename 'Any' to 'All'

**Comment by andrewhancox** [comment]
That's not how this report works (and would be pretty fiddly to change) - it doesn't include good translations, just issues that it's seen with existing/missing ones.
