### ISSUE TITLE
Display the number of missing and stale translations in the currently selected Moodle language on this page in the drop-down menu

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#33]
Display the number of missing and stale translations in the currently selected Moodle language on this page in the drop-down menu.

![image](https://user-images.githubusercontent.com/8575694/159591272-5c5b8e9d-ab4d-44f2-b7c4-9e4275f9ac63.png)
So add a number in the same style as the alerts number. E.g.:
4 translations missing on this page 
3 stale translations on this page

**Comment by andrewhancox** [comment]
Done
