### ISSUE TITLE
Add all missing and stale translations to the drop-down menu as 2 new items

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#34]
Add all missing and stale translations to the drop-down menu as 2 new items
So the drop down menu looks like this - the numbers are for translations in the currently selected Moodle language only:

- Stop in-line translation
- Missing on this page (4)
- Stale on this page (3)
- All missing translations (99+)
- All stale translations (45)

![image](https://user-images.githubusercontent.com/8575694/159592433-181fd035-f6f3-4fa3-9956-586b6f1436c6.png)

**Comment by jgramp** [comment]
Going to the All translations pages, simply adds a / into the Page field.

**Comment by andrewhancox** [comment]
Done
