### ISSUE TITLE
Add the total missing and stale translations on this page (in the currently selected Moodle language only) as an alert in the top navbar to the right of the translation icon

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#35]
![image](https://user-images.githubusercontent.com/8575694/159593238-0fad0c9b-f615-40c9-801b-643ef69c8582.png)

Add the total number of missing + stale translations on this page ( in the currently selected language only) as an alert in the top navbar to the right of the translation icon

Use the same styling as that used for the notifications number.

So on pages that are up to date there is no alert. That will make it easy to see what needs updating without opening the menu.

The frontpage should the total for all pages (/), so when someone first logs in (assuming they see the front page first) they can see the total translations missing. It should show 99+ if there are 100 or more.

**Comment by andrewhancox** [comment]
I've added counts for site wide missing and stale - counts on a context level won't be reliable for architectural reasons.
