### ISSUE TITLE
Rename 'Substitute text' to 'Translated content' on the 'Create translation' page

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#37]
Rename 'Substitute text' to 'Translated content' on the 'Create translation' page, so the meaning is clear and it covers other content like images etc. not just text.

![image](https://user-images.githubusercontent.com/8575694/159593604-4bf738fc-b64f-4876-a1d3-ffc12eb44998.png)

**Comment by andrewhancox** [comment]
Done
