### ISSUE TITLE
Non urgent: make the Substitute text / 'Translated text' as wide as the Original content (50% 50%) and as long

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#38]
![image](https://user-images.githubusercontent.com/8575694/159593526-950a4c2a-b10f-4ba8-83fc-105d8bf3d081.png)

It would be easier to translate if the 'Original content' and the Substitute /'Translated content' is the same width and height.
So as you scroll down the page you can see the equivalent original content in the same relative place as the translated content.

**Comment by andrewhancox** [comment]
Should be about right now... Will be almost impossible to be exact.
