### ISSUE TITLE
Feature to implement: Toggle the Original content to show [ current | old | diff ] content in this space

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#39]
See the idea here, https://tracker.moodle.org/browse/CONTRIB-8706 but I think the best place for the diff is to replace the Original content, so you have 3 tabs at the top:
**Original Content** [**current** | old | diff]

The current content is shown by default. For missing translations you only see a [current] option.

For stale translations, you see 3 options [**current** | old | diff] and can toggle between these to see the different content appear in the space below.

Something like this, with  [ current | old | diff ] in the 3 tabs at the top:

![image](https://user-images.githubusercontent.com/8575694/159595857-ba49f8e3-7fb9-43de-9aa4-a7f9924f63fd.png)

**Comment by andrewhancox** [comment]
Done

**Comment by andrewhancox** [comment]
As discussed, I think this is as good as it can be but will leave it to others to see if they can improve the feature.
