### ISSUE TITLE
Some pages do not have breadcrumb navigation

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-filter_translations#44]
Add breadcrumb navigation so that users can know where they are and can navigate to previous sections without replying on the browser back button.
The following pages do not have any breadcrumbs:

- Edit translations
- Edit translation issues
- Create translations

**Comment by andrewhancox** [comment]
There was originally no link between translations and contexts but I've created one and where possible all pages are in the right context and have the appropriate breadcrumbs etc.
