### ISSUE TITLE
Translated titles allow only 48 characters

### ISSUE THREAD

**Issue by annakrassa** [andrewhancox/moodle-filter_translations#47]
The substitute text when it's to translate titles allows up to 48 characters. We certainly need this much much longer.

**Comment by annakrassa** [comment]
![Screenshot (29)*](https://user-images.githubusercontent.com/100235318/159716485-9b1aa1c0-448f-4832-9f62-2a3cf9ca6cbc.png)

**Comment by andrewhancox** [comment]
Fixed

**Comment by jgramp** [comment]
Thanks Andrew. What's the limit now please?

**Comment by andrewhancox** [comment]
There isn't one.

**Comment by jgramp** [comment]
Thanks for confirming Andrew.
