### ISSUE TITLE
Description text in the Announcements forum has no editor and doesn't fit

### ISSUE THREAD

**Issue by annakrassa** [andrewhancox/moodle-filter_translations#49]
Trying to translate the Announcements forum **description** I noticed that there is no editor as in other activities and the text allowed again is 48 characters.
![Screenshot (27)*](https://user-images.githubusercontent.com/100235318/159717082-6840a088-3424-4be7-b985-b1d9fbe5735f.png)

**Comment by andrewhancox** [comment]
The length of the text is fixed.

The only way to know if I should show an atto editor is by looking for html tags in the raw text which in a tiny minority of cases may not work.

That said I did fix an issue when editing translations from the lister.

**Comment by jgramp** [comment]
So Andrew, if this problem occurs, can we add html tags (like <p>blah blah</p>) and it will then generate a larger text area for us to use in the translation editor?

Would this also work in a non-HTML field. If we were to add HTML tags into a standard (simple) text input field?

**Comment by andrewhancox** [comment]
Yes, any html tags in the raw text would cause it to be a rich text editor. In most cases the atto editor slips in some kind of markup so this should almost always get it right.
