### ISSUE TITLE
Rich text editing - can't see source text

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#5]
When I edit a page, label etc with rich text, I am unable to see the source text in the edit window.

# Label

![image](https://user-images.githubusercontent.com/2512079/152163967-0fae16bb-b4f4-4316-9e18-60be9a2830ab.png)

# Translation details

![image](https://user-images.githubusercontent.com/2512079/152164063-7a2b8e90-1ca9-4cab-b19e-024401d936cb.png)

# Edit translation

![image](https://user-images.githubusercontent.com/2512079/152164148-e013d47f-c694-4dec-87b5-1e5e2407d445.png)

**Comment by andrewhancox** [comment]
Fixed
