### ISSUE TITLE
Exceptions when installing the translation plugins in a new site

### ISSUE THREAD

**Issue by annakrassa** [andrewhancox/moodle-filter_translations#50]
I installed translation plugins in MEC staging site as following:

1. Installed first the atto translations .zip
2. Then system required the translatiosn filter
3. I downloaded the second .zip and proceed. 

Then I got this...

![Screenshot (22)](https://user-images.githubusercontent.com/100235318/159717915-9e00c5cc-af18-4ce4-9e1e-8d5d105d3701.png)

**Comment by jgramp** [comment]
Hi Anna.

Can you describe what happens when you try to use the plugin too? Do the
icons appear? Is everything working the same as it does on Moodle Academy
staging?

Thanks.

**Comment by annakrassa** [comment]
Yes it works normally. Of course, I can't get into stale translations, but that's an issue currently in Academy too. 

Also the icons appear as blank pills in the Navigation drawer, but I think that's a CSS issue already mentioned in another ticket.

**Comment by andrewhancox** [comment]
This is now fixed.
