### ISSUE TITLE
Translations made with the old translation plugin need to be recognised by the new plugin

### ISSUE THREAD

**Issue by annakrassa** [andrewhancox/moodle-filter_translations#52]
In MEC site we have already translated the six MEC courses into 8 languages. I expect that the new plugin will be still able to use the translations made with the old plugin.

**Comment by andrewhancox** [comment]
There is a command line tool to do this:
https://github.com/andrewhancox/moodle-filter_translations#to-migrate-from-filter_fulltranslate

**Comment by jgramp** [comment]
Hi @rjnl @ @annakrassa 
We need to test this ASAP on MEC staging. 
Anna, please can you ensure Rajneel has the site admin access he needs.
@rjnl - please talk to ICT as a high priority to arrange cli access to the MEC staging server.
