### ISSUE TITLE
We need a method to delete translations

### ISSUE THREAD

**Issue by RichieLef** [andrewhancox/moodle-filter_translations#54]
Currently there doesn't seem to be a method to delete existing individual translations. This is a required feature.

Use cases:
1. A user provides a translation that is blatantly/obviously incorrect. Our team don't have the time or expertise to translate it correctly in that moment, so we need to delete that particular translation (rather than just edit it to something else, which would give it a false "translation up to date" status)
2. A user translates a piece of content which includes formatting using the text editor (eg the original content has styled text, links, images etc). Upon saving, the translated content is formatted incorrectly - perhaps because the user made an error using the text editor (eg links or images have broken, styles have been removed or changed). Rather than troubleshooting the translated content to fix the issue(s), the user needs to be able to delete that specific translation to 'start fresh'. 

Perhaps there could be an option to "delete translation" when editing an existing one?
![image](https://user-images.githubusercontent.com/102128709/159858684-b279ef31-596d-4146-a02d-97de92c8cc70.png)

**Comment by andrewhancox** [comment]
Done
