### ISSUE TITLE
Error: Comparisons of text column conditions are not allowed

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-filter_translations#57]
After changing the field of url from varchar(255) to text, we now get the following error on certain pages such as Site administration and login pages:

Comparisons of text column conditions are not allowed. Please use sql_compare_text() in your query.
Debug info:
Error code: textconditionsnotallowed
Stack trace:
line 677 of \lib\dml\moodle_database.php: dml_exception thrown
line 1450 of \lib\dml\moodle_database.php: call to moodle_database->where_clause()
line 814 of \lib\classes\persistent.php: call to moodle_database->get_records()
line 121 of \filter\translations\classes\translator.php: call to core\persistent::get_records()
line 69 of \filter\translations\classes\translator.php: call to filter_translations\translator->checkforandlogissue()
line 67 of \filter\translations\filter.php: call to filter_translations\translator->get_best_translation()
line 176 of \lib\filterlib.php: call to filter_translations->filter()
line 232 of \lib\filterlib.php: call to filter_manager->apply_filter_chain()
line 1488 of \lib\weblib.php: call to filter_manager->filter_string()
line 1233 of \lib\pagelib.php: call to format_string()
line 2849 of \lib\weblib.php: call to moodle_page->set_title()
line 786 of \admin\index.php: call to redirect()
Comparisons of text column conditions are not allowed. Please use sql_compare_text() in your query.
Debug info:
Error code: textconditionsnotallowed
Stack trace:
line 677 of \lib\dml\moodle_database.php: dml_exception thrown
line 1450 of \lib\dml\moodle_database.php: call to moodle_database->where_clause()
line 814 of \lib\classes\persistent.php: call to moodle_database->get_records()
line 121 of \filter\translations\classes\translator.php: call to core\persistent::get_records()
line 69 of \filter\translations\classes\translator.php: call to filter_translations\translator->checkforandlogissue()
line 67 of \filter\translations\filter.php: call to filter_translations\translator->get_best_translation()
line 176 of \lib\filterlib.php: call to filter_translations->filter()
line 232 of \lib\filterlib.php: call to filter_manager->apply_filter_chain()
line 1488 of \lib\weblib.php: call to filter_manager->filter_string()
line 1233 of \lib\pagelib.php: call to format_string()
line 2853 of \lib\outputrenderers.php: call to moodle_page->set_title()
line 1950 of \lib\setuplib.php: call to core_renderer->fatal_error()
line 390 of \lib\setuplib.php: call to bootstrap_renderer->__call()
line ? of unknownfile: call to default_exception_handler()

**Comment by andrewhancox** [comment]
Fixed
