### ISSUE TITLE
The message about stale translations on the Edit translation page should not be able to be closed. It should always be visible

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#59]
The message about stale translations (and any other similar alerts for missing / up to date translations) should not be able to be closed. This message should stay there, so the translator knows it's stale. Can we remove the cross that let's you close the message, so it doesn't disappear?

![image](https://user-images.githubusercontent.com/8575694/161173952-6030b053-b0a9-43f0-820e-561be57f93c7.png)

**Comment by andrewhancox** [comment]
CSS to hide the cross?

**Comment by jgramp** [comment]
That would work.

**Comment by jgramp** [comment]
It'd be good to include that in the plugin, so it's fixed for everyone.
