### ISSUE TITLE
P2: Add some truncated translate text, so you can see what the hash refers to.

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#70]
Manage pending translations‍‍​‍‍ page should show some of the truncated translated text, similar to how the Original content is displayed truncated:
https://next.moodle.academy/filter/translations/managetranslationissues.php
![image](https://user-images.githubusercontent.com/8575694/164128443-a8119fa5-ad79-4985-a90b-1eb3b3425da9.png)

**Comment by andrewhancox** [comment]
Done

**Comment by jgramp** [comment]
I don't see any translated text column at all:
![image](https://user-images.githubusercontent.com/8575694/168054238-1042ee68-e3b3-436c-a8e1-5408632481eb.png)

**Comment by andrewhancox** [comment]
Mis-read and thought it was a duplicate, now sorted.
