### ISSUE TITLE
P2: Add a search box to search by content (text search)

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#71]
We want to be able to search by original or translated content on the Manage pending translations‍‍ page.
https://next.moodle.academy/filter/translations/managetranslationissues.php

Also, requires translated content 'P2: Add some truncated translate text, so you can see what the hash refers to.':
https://github.com/andrewhancox/moodle-filter_translations/issues/70 

Would these search boxes go under filter options?
![image](https://user-images.githubusercontent.com/8575694/164128549-bf593ebf-510c-44b9-9dca-0072730bec90.png)

**Comment by andrewhancox** [comment]
Done

**Comment by jgramp** [comment]
I can't see a content search box:

![image](https://user-images.githubusercontent.com/8575694/168053940-1fa11e46-27bf-482f-b4d8-1102e38581fa.png)

**Comment by andrewhancox** [comment]
I hadn't added it to the issues table as it didn't think you'd want it there but have gone back and added it in. Have also added ability to search the substitute text as well.
