### ISSUE TITLE
We need a way to view the HTML of the original content in case anything is removed by Atto that needs to be retrieved.

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#72]
We need a way to view the HTML of the original content in case anything is removed by Atto that needs to be retrieved.

When editing a button for example the button styles were removed and there's no easy way for a translator to see the code unless they happen to be a developer who know hows to use the page inspector.

**Comment by andrewhancox** [comment]
Added a tab to the edit translation form
