### ISSUE TITLE
Minor: what happens when missing translations on this page passes 999?

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#74]
Once we reach >999 changes we can just write 999+?
Seems ok for now, but just raising this in case it causes problems with large numbers in future.
If it looks ok with 1000s we can just ignore this.

Currently it looks like this:
![image](https://user-images.githubusercontent.com/8575694/164130666-899c436a-7e07-411c-a962-86ac9126bdf8.png)

**Comment by andrewhancox** [comment]
Done at 99 as per spec. Can change to 999 if desired.
