### ISSUE TITLE
Translation overrides cannot be switched on

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#8]
Using Moodle 3.11 with plugin version: 2022012400

Add French language pack.

Enabled content translations filter for content and headings.

When clicking the inline translation button:

Expected behaviour: Icons should appear by each text element to allow translation

Actual behaviour: No icons appear

**Comment by berthelemy** [comment]
Not sure how, but this is now working.

What I'd done in the meantime:
- Add locales to the Bitnami VM (to try to fix error message in Moodle saying locales not installed)
- Restart Apache

**Comment by andrewhancox** [comment]
I would expect the whole thing to behave erratically if the relevant locales were not installed on the server - isn't this a requirement already? Without this all the core PHP localisation stuff will be broken.

**Comment by berthelemy** [comment]
Yes, I did wonder.
The Bitnami VM had en_us utf8 only switched on.
I've tried switching on en_gb and fr.
I still get this message when going to the language packs:

Your server does not seem to fully support the following languages:

English ‎(en)‎
Français ‎(fr)‎
Instead, the global locale (en_AU.UTF-8) will be used to format certain strings such as dates or numbers.

Not sure what I need to do to fix this. But it looks like it's only an issue for dates and numbers. Although I am finding the language menu is showing Spanish (en), instead of English (en). That happened the first time I was testing this plugin when the plugin was working OK. So I wasn't too worried.

Having spent way too long trying to get a test instance set up on my Macbook, I gave up and went with Bitnami on Google Cloud. Normally these work fine.

**Comment by hribeir0** [comment]
Only after dealing with that message have I gone for translation filters. While I use WSL and Ubuntu I do "sudo apt install locales-all && sudo locale-gen"

**Comment by berthelemy** [comment]
@hribeir0 Even after running "sudo apt install locales-all && sudo locale-gen", I still get this error in Moodle:

> Your server does not seem to fully support the following languages:
> English ‎(en)‎
> Français ‎(fr)‎
> Instead, the global locale (en_AU.UTF-8) will be used to format certain strings such as dates or numbers.

On running the command, the console shows:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  locales-all
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 10.7 MB of archives.
After this operation, 227 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 locales-all amd64 2.28-10 [10.7 MB]
Fetched 10.7 MB in 0s (39.2 MB/s)
Selecting previously unselected package locales-all.
(Reading database ... 55370 files and directories currently installed.)
Preparing to unpack .../locales-all_2.28-10_amd64.deb ...
Unpacking locales-all (2.28-10) ...
Setting up locales-all (2.28-10) ...
Generating locales (this might take a while)...
  en_GB.UTF-8... done
  en_US.UTF-8... done
  fr_FR.UTF-8... done

**Comment by hribeir0** [comment]
Have you restarted the server? Might be useful checking https://moodle.org/mod/forum/discuss.php?d=390750 and https://docs.moodle.org/dev/Table_of_locales

**Comment by andrewhancox** [comment]
Did you restart Apache/NginX etc... ?

**Comment by berthelemy** [comment]
Closing this, as this is just a test site. I did everything people suggested above.
