### ISSUE TITLE
Moodle Workplace compatibility: For workplace languages (ending in _wp) save content translations to parent language

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#81]
Workplace uses language packs that are children of the parent language and siblings to the other child languages. Therefore, there is no parent/child relationship when using languages ending in  _wp instead of the parent.

Therefore, in order for French language translations (for example), to be used by French Canadian, we will need to save an translations against a Workplace language to its parent instead.

I.e.
Check if the language short name ends in (_wp).
If it does, save the translation against its parent language instead.

E.g. 
If the current translation language is French for Workplace (fr_wp).
Save the content translation to its parent French instead (fr).

This will ensure that all the child languages will pick up the language translations of its parent, when no translation exists for the child language itself.

**Comment by andrewhancox** [comment]
I think this is an architectural issue with workplace - unless a full suite of child language packs is going to be developed something needs to be done to adjust the way the hierarchy works... maybe allow the Moodle core child packs to show the _wp as their parent, would need a lot of thought.

**Comment by jgramp** [comment]
Yes, it's complicated and there seem to be no moves internally to change the way it works, so we'll have to work around it for now. I see no issues with my proposed solution and I have passed this by our solutions architect here for Moodle Workplace and no issues were raised. It will ensure the language translations can be exported out of a workplace site too and moved into a Moodle LMS site without issues. This is important to us.

@rjnl will be able to start looking at this proposed solution next week.

**Comment by rjnl** [comment]
@andrewhancox  - Please see if the following commit is an appropriate way to handle this:
https://github.com/andrewhancox/moodle-filter_translations/commit/cfcf434888a957e490b059194dbeec5aa08df21f

**Comment by rjnl** [comment]
Fix merged.

**Comment by rjnl** [comment]
@andrewhancox : This issue can be closed.
