### ISSUE TITLE
Long page URLs push out the page column to be much too wide, so you need to scroll to see the other columns

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#82]
Long page URLs push out the page column to be much too wide, so you need to scroll to see the other columns.
Can the URLs be truncated (but still linked), like the Original content column is?
![image](https://user-images.githubusercontent.com/8575694/165540342-a5f5fc18-c923-44f7-b419-970831d4eac0.png)

**Comment by andrewhancox** [comment]
Done
