### ISSUE TITLE
Coding problem: $PAGE->context was not set

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#85]
Hi Andrew,

We're getting this error when debugging is turned on. It's at the point where the page tries to get page context information.

Moodle version: 3.10

Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result

• line 503 of /lib/pagelib.php: call to debugging()
• line 830 of /lib/pagelib.php: call to moodle_page->magic_get_context()
• line 195 of /filter/translations/filter.php: call to moodle_page->__get()
• line 159 of /filter/translations/lib.php: call to filter_translations::checkinlinestranslation()
• line 1064 of /lib/setup.php: call to filter_translations_after_config()
• line 32 of /config.php: call to require_once()
• line 26 of /admin/purgecaches.php: call to require_once()

**Comment by berthelemy** [comment]
Hi @andrewhancox ,

We're still getting this debugging issue:

Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result

• line 503 of /lib/pagelib.php: call to debugging()
• line 830 of /lib/pagelib.php: call to moodle_page->magic_get_context()
• line 150 of /filter/translations/filter.php: call to moodle_page->__get()
• line 90 of /filter/translations/filter.php: call to filter_translations->addinlinetranslation()
• line 176 of /lib/filterlib.php: call to filter_translations->filter()
• line 232 of /lib/filterlib.php: call to filter_manager->apply_filter_chain()
• line 1488 of /lib/weblib.php: call to filter_manager->filter_string()
• line 64 of /user/profile/field/menu/field.class.php: call to format_string()
• line 599 of /user/profile/lib.php: call to profile_field_menu->__construct()
• line 930 of /user/profile/lib.php: call to profile_get_user_fields_with_data()
• line 3422 of /lib/moodlelib.php: call to profile_has_required_custom_fields_set()
• line 2795 of /lib/moodlelib.php: call to user_not_fully_set_up()
• line 58 of /course/view.php: call to require_login()

**Comment by andrewhancox** [comment]
Still can't reproduce but have put in a fix that should handle it.
