### ISSUE TITLE
The Original HTML tab content runs behind the text editor.

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#89]
![image](https://user-images.githubusercontent.com/8575694/168052050-287f714c-cf36-4224-8bdb-25653aae2575.png)
The Original HTML tab content runs behind the text editor.
It should wrap so it sits next to the editor, not behind it.
/filter/translations/edittranslation.php#rawhtml

**Comment by andrewhancox** [comment]
Fixed
