### ISSUE TITLE
Google translate only translating some strings

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#9]
I have a small test course with:
- Longname
- Shortname
- Description
- Contents including a label and a topic heading

Only the description is translated.

The course name is left as English, but marked up in the translations table as French.

Both shown in the image below:
![image](https://user-images.githubusercontent.com/2512079/155327278-04d95757-a2eb-46ba-abd6-7a9a49e7818b.png)

The course content doesn't seem to be even calling the Google API.

**Comment by berthelemy** [comment]
Yes, see below:
![image](https://user-images.githubusercontent.com/2512079/155339222-082c073f-cba6-45ae-afc1-1689b16430cc.png)

It's the last filter in the list.

**Comment by andrewhancox** [comment]
There was an issue due to Moodle tresating English being treated as the parent language for everything and so cached English translations were showing up as being 'close enough'. Now sorted.
