### ISSUE TITLE
YouTube video code (iframe) stripped out of translation editor

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#93]
YouTube video code (iframe) stripped out of translation editor
![image](https://user-images.githubusercontent.com/8575694/168628554-8163c531-dfa3-4840-a944-2ee19ca805fd.png)

Had to manually copy and paste the youtube video code back in:
<iframe width="560" height="315" src="https://www.youtube.com/embed/dZNC5kIvM00" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>

**Comment by andrewhancox** [comment]
Fixed
