### ISSUE TITLE
Sometimes the language and Translation hash key aren't loaded into the editor on an up to date translation

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#96]
I made a translation in german as a simple translator (user with the one translation permission) and then went in as another admin user (with full permissions) and I can see the german translation, but when I go to edit it, it loses the language and just chooses the default first language and the hash key is empty:
![image](https://user-images.githubusercontent.com/8575694/168636482-0be58af8-70c1-4ce8-a458-411d05f2d334.png)

The icon says the translation is up to date, which it is:
![image](https://user-images.githubusercontent.com/8575694/168636862-0b00673a-d4ed-42ef-a0b2-258a83b6d8b6.png)

but when I click I'm getting:
![image](https://user-images.githubusercontent.com/8575694/168636959-f339fc46-396c-4438-af1d-c66a7b2d2fd4.png)

**Comment by jgramp** [comment]
other times I edit an up to date translation and it finds the hash:
![image](https://user-images.githubusercontent.com/8575694/168637267-7e1000b5-dca9-49ea-8abc-90c51ef972c1.png)

But when I click edit translation in the pop up, the language has been lost and it shows the first language:
![image](https://user-images.githubusercontent.com/8575694/168637569-8dd7886f-5229-45b9-befa-ef9b50dc9c62.png)

**Comment by andrewhancox** [comment]
Looks like a WP issue
