### ISSUE TITLE
When any user (site admin or a normal user without editing rights) adds a picture and a document into a translation the files are broken:

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-filter_translations#97]
When a normal user without editing rights adds a picture and a document into a translation the documents are broken:
![image](https://user-images.githubusercontent.com/8575694/168643319-ea0137c0-77b9-4a96-a5e7-fc908de40d44.png)

![image](https://user-images.githubusercontent.com/8575694/168643384-fd71363b-8ca8-48fc-83a4-57af21cbe57b.png)

**Comment by jgramp** [comment]
same issue happens for admins:
![image](https://user-images.githubusercontent.com/8575694/168643791-da2f4537-77a7-40a7-bbaf-818f0b36d96e.png)

**Comment by andrewhancox** [comment]
Fixed
